### ISSUE TITLE
Set up Penguin Watch for Facebook

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/penguin-watch-fb#2]
This is now deployed via Docker, and rebuilds on changes to master. There's a dev app on FB, and remaining features are:
- [ ] Bring up to date with current [Penguin Watch](https://github.com/zooniverse/penguinwatch)
- [ ] Disable / hide the `TopBar` component
- [ ] Extend the `Classifier` class to add the news feed posting feature in [WGFB](https://github.com/zooniverse/wildcam-gorongosa-facebook)
- [ ] Publish the app on FB

@chrislintott for reference

@eatyourgreens I'm taking [some overrides from Science Gossip](https://github.com/zooniverse/sciencegossip/blob/master/overrides.coffee) as a how to for extending the `Classifier` and amending the template to include a new FB Share button - I may need some advice if I get stuck

**Comment by eatyourgreens** [comment]
This is all done now, isn't it?
