### ISSUE TITLE
Breaking when viewed on FB Canvas

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/penguin-watch-fb#3]
When viewed on FB, the project breaks fairly hard. After talking to @parrish, I think there's a couple of things that need to be fixed, but I'm not sure how with the older readymade projects:
1. In [`project.coffee`](https://github.com/zooniverse/penguin-watch-facebook/blob/master/project.coffee#L37):
   
   ``` coffee
   [apiHost, apiProxyPath] = if window.location.hostname is 'www.penguinwatch.org'
     ['https://www.penguinwatch.org', '/_ouroboros_api/proxy']
   else
     [null, null]
   ```
   
   Can we just set the `apiHost` directly, and what should it be in this case?
2. Is there anything else that needs to be done to bypass the proxy frame?

Sorry for spamming you with questions, but would you mind helping me out?

**Comment by rogerhutchings** [comment]
Okay, first thing - the dockerfile is using the node argon image, and penguins _silently_ breaks when not on 0.10 - 63d9324be742beafde52d528270848d34ed1a147

**Comment by eatyourgreens** [comment]
That's very weird. I don't have node 0.10 and readymade projects shouldn't need it.

**Comment by rogerhutchings** [comment]
Definitely happens - causes an error where it tries to set SVG dimensions to `NaN`. You can reproduce it locally with nvm

**Comment by rogerhutchings** [comment]
Sorry, tell a lie, it was `0.12`

**Comment by eatyourgreens** [comment]
Interesting. That error shows up in the web version, but browsers just ignore it and move on.
