### ISSUE TITLE
Event error when running in production

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/penguin-watch-fb#5]
I'm consistently getting the following error when running this in production. 

```
Uncaught TypeError: Cannot read property 'preventDefault' of undefined(…)
```

It's occurring in the `marking-surface` library, in the `Tool.prototype._onStart` method. 

At first I thought it was a transient error, and it took me ages to replicate the exact circumstances which cause it. Now I can do it consistently by following these steps:

- Check out the `more-fb-updates` branch
- Build the app
- Run a static server inside the `build` directory (to recreate the production environment)
- Classify a subject with some penguins in (a blank / can't tell classification works as normal)
- Error is produced, and the classification summary doesn't show

I thought it was my overriding the classification summary to begin with, but it happens regardless of whether it's included or not.

I've been digging away at this for ages with no luck - @parrish or @eatyourgreens, can you shed any light on what's going on here?

**Comment by eatyourgreens** [comment]
I'll take a look. It's been a while since I looked at the marking surface library but, from memory, `onStart` fires when a mark is first created, so it sounds like it is trying to draw even when you haven't clicked on the SVG image.

**Comment by rogerhutchings** [comment]
After having a look with @eatyourgreens yesterday, we found a few things:
- PW is setting its own API host regardless of the `IS_DEV` flag
- Jim discovered that it's working on higher port numbers because `classification.send()` isn't being called
- On lower port numbers, it might be that the request body includes the marking tool objects, which aren't serializable

@parrish is any of this ringing bells for you? Is there anything special needed to serialize data for posting to Ouroboros?

**Comment by parrish** [comment]
Looks like readymade checks the port or looks for a `dev` query param to set that.  Adding `?dev=false` to the url should disable that.

**Comment by eatyourgreens** [comment]
I found that `API.request` is crashing if the `data` parameter that's passed in is a classification containing marking tools in the annotations array. I'm not completely sure why that's happening, but it might be that jQuery's ajax method doesn't like data if it doesn't contain simple objects composed of key-value pairs. So maybe `data` needs to be sanitised somehow before the POST request is made?

**Comment by eatyourgreens** [comment]
Here's the line that seems to be failing when saving a classification https://github.com/zooniverse/penguin-watch-facebook/blob/more-fb-updates/api.coffee#L24

**Comment by eatyourgreens** [comment]
I've looked a bit more at this. This array of annotations will save without errors:

``` json
[{"key":"animalsPresent","value":"yes"},
{"key":"marking","value":[]},
{"key":"allPenguinsMarked","value":"incomplete"},
{"started_at":"Sat, 05 Nov 2016 15:39:47 GMT","finished_at":"Sat, 05 Nov 2016 15:40:15 GMT"},
{"user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"},{"workflow":"untitled_workflow"},
{"lang":"en"}]
```

This one throws an error when jQuery tries to generate form data for the POST request.

``` json
[{"key":"animalsPresent","value":"yes"},
{"key":"marking","value":[{"value":"adult","frame":0,"x":708.383,"y":215.783}]},
{"key":"allPenguinsMarked","value":"incomplete"},
{"started_at":"Sat, 05 Nov 2016 15:40:44 GMT","finished_at":"Sat, 05 Nov 2016 15:40:59 GMT"},
{"user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"},{"workflow":"untitled_workflow"},
{"lang":"en"}]
```

The only difference is that the second one has a marking annotation, but I can't see what's causing the problem.

**Comment by eatyourgreens** [comment]
OK, the proxy frame for Ouroboros passes data around as JSON strings, so it goes through `JSON.stringify` and `JSON.parse` before being passed to `$.ajax`. https://github.com/zooniverse/Ouroboros/blob/master/app/assets/javascripts/proxy.js.coffee#L220

I added the following code to `API.request`

``` coffeescript
if typeof data is 'object'
      tmp = JSON.stringify data
      console.log tmp
      data = JSON.parse tmp
      console.log data
```

and voilà, classifications started to work here too.

I think the mark objects have some underscored event properties, which are stripped out by the JSON conversion.
